clc; clear all
display('------------------------------------------------------------')
display('-                       START (Step 02)                    -')
display('------------------------------------------------------------')

%%%%%%%%%%%%%%%%%%%%%%%%% USERS DEFINITIONS %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
addpath('C:/CIMNE/toolsSVD/methods/matlab')
nE   = 9; % number of elastic snapshots (el menor de todos los modos)
nPos = 90; % number of Inelastic snapshots (diferencia entre la cant. total y en el nE mayor)
snpFolder=[ ...   
%     'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/RVE_Struct_Hole_01/Modo01/';  ...   
%     'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/RVE_Struct_Hole_01/Modo02/';  ...
%     'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/RVE_Struct_Hole_01/Modo03/';  ...
    'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/RVE_RigidHole_05/Modo01/';  ...   
    'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/RVE_RigidHole_05/Modo02/';  ...
    'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/RVE_RigidHole_05/Modo03/';  ...
    'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/RVE_RigidHole_05/Modo04/';  ...
    'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/RVE_RigidHole_05/Modo05/';  ...
    'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/RVE_RigidHole_05/Modo06/';  ...
    'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/RVE_RigidHole_05/Modo07/';  ...
    'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/RVE_RigidHole_05/Modo08/';  ... 
%     'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/RVE_Hole_05/Modo(Psi)-01/';  ...   
%     'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/RVE_Hole_05/Modo(Psi)-02/';  ...
%     'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/RVE_Hole_05/Modo(Psi)-03/';  ...
%     'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/RVE_Hole_05/Modo(Psi)-04/';  ...
%     'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/RVE_Hole_05/Modo(Psi)-05/';  ...
%     'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/RVE_Hole_05/Modo(Psi)-06/';  ...
%     'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/RVE_Hole_05/Modo(Psi)-07/';  ...
%     'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/RVE_Hole_05/Modo(Psi)-08/';  ...    
%     'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/RVE_Hole_05/Modo09/';  ...   
%     'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/RVE_Hole_05/Modo10/';  ...
%     'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/RVE_Hole_05/Modo11/';  ...
%     'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/RVE_Hole_05/Modo12/';  ...
%     'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/RVE_Hole_05/Modo13/';  ...
%     'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/RVE_Hole_05/Modo14/';  ...
%     'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/RVE_Hole_05/Modo15/';  ...
%     'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/RVE_Hole_05/Modo16/';  ...    
%     'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/RVE_Hole_05/Modo17/';  ...  
%     'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/RVE_Hole_05/Modo18/';  ...    
%     'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/RVE_Hole_05/Modo19/';  ...   
%     'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/RVE_Hole_05/Modo20/';  ...
%     'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/RVE_Hole_05/Modo21/';  ...
%     'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/RVE_Hole_05/Modo22/';  ...
%     'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/RVE_Hole_05/Modo23/';  ...
%     'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/RVE_Hole_05/Modo24/';  ...
%     'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/RVE_Hole_05/Modo25/';  ...
%     'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/RVE_Hole_05/Modo26/';  ... 
%     'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/TEST13/Modo01/';  ...   
%     'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/TEST13/Modo02/';  ...   
%     'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/TEST13/Modo03/';  ...   
%     'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/TEST13/Modo04/';  ...   
%     'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/TEST13/Modo05/';  ...   
%     'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/TEST13/Modo06/';  ...   
%     'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/TEST13/Modo07/';  ...   
%     'C:/CIMNE/Codes/MultiScale_SantaFe/Examples/TEST13/Modo08/';  ...   
	  ]; 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%  
%try
%    matlabpool close
%catch
%    n_workers = size(snpFolder,1);
%    matlabpool('open', n_workers)
%end  
for i=1:size(snpFolder,1)
   FuncCreateStrainSnapShotsHardeningFromMatFile(snpFolder(i,:), nE, nPos);
end

  
% if(size(snpFolder,1)==1)
%     FuncCreateStrainSnapShotsHardeningFromMatFile(snpFolder(i,:), 10, 30);
% else
%     for i=1:size(snpFolder,1)
%         % Store Snapshots in .mat file
% %         FuncCreateStrainSnapShotsHardeningFromMatFile(snpFolder(i,:), 3, 500);
%         FuncCreateStrainSnapShotsHardeningFromMatFile(snpFolder(i,:), nE, nPos);
%     end
% end
